### PR TITLE
Fix several grammar issues and typos in the documentation

### PR DESCRIPTION
**Pull request by wanderer163**

### CODE REVIEW

**Comment by merrcury** [comment]
@wanderer163 Can you please sign our CLA?

**Review by merrcury — APPROVED** [review]
LGTM

**Comment by wanderer163** [comment]
> @wanderer163 Can you please sign our CLA?

I have signed it, but the status isn't reflecting. Would you know why? I have clicked on the "recheck" CLA status button as well.

**Comment by merrcury** [comment]
Merging as CLA found to be signed

**Review by merrcury — APPROVED** [review]

**Pull request merged**
